Fix: memo decode not working on special characters
chain4travel/camino-block-explorer-old pull request #22
Opened 2022-05-18 11:36 UTC by Ayagoumi

Fix: memo decode not working on special characters

2022-05-18 11:59 UTC, nhamley requested changes

2022-05-18 11:59 UTC, nhamley commented on src/stores/magellan-tx-store.ts
> +    return decodeURIComponent(escape(memo));
hmm on my machine it doesn't seem to work (the memo is still base 64 encoded and not human readable in the fe).

My vs code also says, that escape is deprecated, so i'm not sure it's the best idea to use it

2022-05-18 12:51 UTC, Ayagoumi commented on src/stores/magellan-tx-store.ts
> +    return decodeURIComponent(escape(memo));
I have made changes, the first time I forgot the Atob(). But now i think it's working fine.

2022-05-19 06:19 UTC, nhamley approved these changes

2022-05-19 07:10 UTC, merged